name: "SMTP to MQTT"
version: "v1.0.1"
slug: smtp2mqtt
description: "Transform SMTP to MQTT"
url: "https://github.com/boecks/hassio-addons/tree/main/smtp2mqtt"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
map:
  - share:rw
ports:
  25/tcp: 25
options:
  mqtt_host: "localhost"
  mqtt_port: 1883
  mqtt_topic: "smtp2mqtt"
schema:
  mqtt_host: str
  mqtt_port: port
  mqtt_topic: str
  mqtt_user: str?
  mqtt_pass: password?
  smtp_auth_required: bool?
  smtp_relay_host: str?
  smtp_relay_port: port?
  smtp_relay_user: str?
  smtp_relay_pass: password?
  smtp_relay_starttls: bool?
  smtp_relay_timeout_secs: int?
  publish_attachments: bool?
  save_attachments: bool?
  save_attachments_dir: str?
  debug: bool?
image: "ghcr.io/boecks/docker-smtp2mqtt-{arch}"
